[pytest]
# marks
markers =
    validate_csv: mark tests that validate CSV content
    unmarked: tests that had no explicit marks
# python_files
python_files = test_*.py
# addopts
addopts = --html=report.html --self-contained-html -q