[pytest]
# marks
markers =
    validate_csv: mark tests that validate CSV content
    unmarked: tests that had no explicit marks
# python_files
python_files = test_*.py
# addopts
addopts = --html=report.html --self-contained-html -q
# reportportal
rp_endpoint = https://reportportal.epam.com
rp_api_key = my_api_key
rp_launch = Pytest_Homework_Launch_1
rp_project = STEPAN_ZHUK_PERSONAL
rp_enable = True
rp_log_batch_size = 20